language: ruby
rvm:
- 2.2.1
addons:
  postgresql: '9.4'
script:
- RAILS_ENV=test bundle exec rake db:migrate && bundle exec rspec
before_script:
- psql -c 'create database stolen_bike_alerter_test' -U postgres
cache: bundler
sudo: false
notifications:
  email:
    on_success: never
     on_failure: never
env:
  global:
  - CODECLIMATE_REPO_TOKEN=b67e61788c189f096147eb84e5d0b2f0097ebe985d17125218c1b00bfd17448c
  - secure: dQTqL3OBHczRoBp2LSGZShi3DU4na3kW4l3JbGWvGoQPYik7gTAK33feBqDn34wJwVDneQ6dRDs2SHVFPhcwbtiriurWAQo9UQCp3X513KUBKWlYwCR5WON9M3RmPg7c08NV9cLBjYAtTltofIfTld4WgA6NeaW9b6QaTIfMGc8=
  - secure: S0nAhJNYn9ELPfuoCdjKKqjX+7ypQ3MzeOqJytlGy2WbFhIngDp2oPgqK7I0Pi39O/MV2t9WNZppTK+KHcp/xv7g8+SbOuHHuyU1W47dasrvIJ71YXwCMxGiiSDm57LhA2yuOYCgIWEncok0vsFRtRh077dvn3J3PNZsFMy1ahg=
  - secure: gjtMxEEWvoAe9XsFkH+IXOxmM67FPGR8P2ZVW1YiZOne9Urk4IaHd7sMSk0imZ6WY8zwaBSjTvyoB0M7FR7vNZ8NwQx0vZ1rTMydnqn1tAGe4KT7vj5eesTCi6O3WjujabegWcPS4+iqKfpEJSmKIahWev/r50oV8a21sIfwEGI=
  - secure: YyXGZbmRVPXO6VxsiNjND6pDtHOhPPU818G7YBefB/Kz+isJBq5dvjTP7lXU6oDKkYcr+w+eICQjoaVd+x8TN6NpG2DtLAaksHFUhmEc855CsfC4qUh7Lae2cH5nhNgKevpSyhs6RC167/7jM64dqQ4ucqOrIyxKdUHamnkYLHY=
  - secure: Y8PQxZCIv8QvHPIE7zL2sjv8JMzB/cR17P5R1Bv/fJ4CVrw1fBlPEK8n02rKrPxjkIRTbZl3sqQBeED3gDQo7c09p2NGHNfDE5Q+lMGI+kZ7dT5vnkGjFsvEVOraHd+jh90umXsArXtGFS2tbhPPihsP2mlNJjES8yAwxbTPuXE=
  - secure: e7uIR9patOot0QMZMEsn6HSBxe1ntzXB6mMZGhwRbf8zC0UGXIzOYU4J/o3pmTYi8ydVgorce3chC4yf7hugbA+oBJ4m7VnUR8zyeGZCnccf2pOOt/zQBsG8AqMV7HMbop68lO/5EFunAIGNryxhRYE/p39fZYwn4oaZ+Ppt+SE=
  - secure: m5XgArAV6o2YIH1akdUBBVb2GQEZDwilGAXfN5LDklWwsritX7BgwscMfctFOCEVJ9dT59WChDi+9aSX2BOq4B72n7Ftna9t06/qlp1U1heVc0VnewRI5wc1/zjcNzjRXF2LbBx81ADXa1kegZHm0txB3sjZ8LPeaJkftZohepo=
  - secure: BUiU9FGjFPVttlWJq1Q11lTIXdbqz17wBGqfZk3RmUExKNgH42oKM30gHLBArGAWw0inY6uW3cOhS05BdBe/9xNUS5MD4fgM9JhJMSV3sQRj8lq0W422bA+qKLZkdnQtWv3UTY+qN7SL347IszJ5aE6SYUQqwtnZRodNGrwGuYQ=
  - secure: EEJnadXh4xTXuBXuBQqIUcI51ZTZvcgl1/Egt5Dt6G9r3OhFMdq8I6UaoDlDuWB/z5Q7yoP8JRKMpGK2HRdCbGhnNxoNzpQC5GjtNfMGSC7YOOoATJRtblg2/hlI4h68BF6V8kpSoAV4uAGsorVrR+5jvgec0aC0zSe+ITZMFbI=
  - secure: kL36+G/Ds/WyE1bW2zzi2NZ1IB5DbrligFt/YQqcKhPBoUtMOuqwS3dzarHXti89ypC4cyGhxZd+tlbG+bliF7+MfEY6jJ1CBiATLyb9I691CFJSGfIdUWye8qGDeZrq5DIWsmiBOYOKIMAzFraCJNClj0Te6pC7jMM9a15sUTo=
  - secure: JwO3q1YfWK+PCMTv/3YI49syXoa2g5HTIZw7A+lKltQWAfd4jXFPkgllaIPfFvn8YlLxp7ThctnwlttBGCFnrLid0nsOrAOK0T6a/4vFscHXl9uYgYQ1RaBSUrIl/2advpOyR0ryBYe3L/7cM5YUHX3K3ysXCyHiyCZrRT4afaY=
  - secure: Tvw3EXvoKvKK23dd1e6ODqvvmNRtiMIRktLQX7nXN7UNbfh5CQ4PAbup9SlMpGpdQ7wc8skWmY/gw9J36CoOI05gyQR9Eq4iWRoQAQxZimpxao06fjvnJHp//oXpjQhPo97rZd+VjTDWdKi/DZXsssmJc3C9zpMe7mFBxlOLZFQ=
  - secure: Xa6ni6C08Nu5g4T9lhC+3X7AJTSnt4eymsuzIKrvTh899W3PokBzdaslpuT7JhPF62uaAd1Ev6RKWsx5xboTYJPQBf6AFtz851OTN7XncLCJ2ql/uy3wuVhdpKA1g1MhMIK6WVNlJvG+3dgNpoGebFXv14zOw+i3XhtqCqHnyA0=
  - secure: MXyTUAwITn7emVoERa8aIDCAqvEx4OHACusjDUnwSJEGMijxKNqELO8Z80QFMRKTXiRlJStr6GraGh7Alvx92pybh1zKGst3CL6BIUzlNl4lzuXaVSdl7aw8KC0sW9gmmR7/6hlDrvYvnm782cETJEsMK+DPLudLDGEjdr58Gso=
  - secure: gUwYBOSHDUnWo9E8wG5Xi4y1yAUahYHRn4oekBEEprMQFm2oPONYauiR2RRRR4j7ZOMqr71mL5EihARbs43SWRG4w09C5ypBHFJLXRfpimrYeTHY/769qiTdaeRPOjCYx3cZhTU98eIfDiqrQHIgdOcHJKe8y/9QmKxgI1u1fWk=
