
default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5

development:
  <<: *default
  database: stolen_bike_alerter_development

test:
  <<: *default
  database: stolen_bike_alerter_test

production:
  <<: *default
  database: stolen_bike_alerter_production
